/**
 * report.mjs — renders audit results as markdown.
 *
 * The report is written for a human deciding what to do next, so it leads with
 * the ranked fix list rather than the full check inventory. The inventory
 * follows for anyone who wants to argue with a verdict.
 */

import { CATEGORIES, prioritise } from './checks.mjs';

const ICON = { pass: '✓', warn: '!', fail: '✗', skip: '–' };

function bar(score) {
  if (score === null) return 'n/a';
  const filled = Math.round(score / 10);
  return `${'█'.repeat(filled)}${'░'.repeat(10 - filled)} ${String(score).padStart(3)}%`;
}

function band(score) {
  if (score === null) return 'not scored';
  if (score >= 85) return 'strong';
  if (score >= 65) return 'workable';
  if (score >= 40) return 'weak';
  return 'critical';
}

export function renderMarkdown(audit) {
  const { signals, categories, surfaces, overall, results } = audit;
  const ranked = prioritise(results);
  const lines = [];

  lines.push(`# Visibility audit — ${signals.manifest?.name || signals.repo.dirName}`);
  lines.push('');
  lines.push(`_Generated by RepoRise v${audit.version} at ${audit.generatedAt}. Offline pass — no network was used._`);
  lines.push('');

  lines.push(`## Overall: ${overall}% (${band(overall)})`);
  lines.push('');
  lines.push('| Surface | Score | What it measures |');
  lines.push('| --- | --- | --- |');
  lines.push(`| SEO | ${surfaces.seo ?? 'n/a'}% | Ranking in web search for developer intent queries |`);
  lines.push(`| AEO | ${surfaces.aeo ?? 'n/a'}% | Being lifted into a direct answer or snippet |`);
  lines.push(`| GEO | ${surfaces.geo ?? 'n/a'}% | Being retrieved and cited by a generative engine |`);
  lines.push('');
  lines.push('These three overlap heavily. A check usually moves more than one, which is why the fix list below is ordered by combined impact rather than by category.');
  lines.push('');

  lines.push('## Category scores');
  lines.push('');
  for (const [key, cat] of Object.entries(categories)) {
    lines.push(`**${cat.label}** (weight ${cat.weight}) \`${bar(cat.score)}\``);
    lines.push('');
    lines.push(`${cat.blurb}`);
    lines.push('');
    lines.push(`${cat.counts.pass} passed · ${cat.counts.warn} warnings · ${cat.counts.fail} failed · ${cat.counts.skip} unverified`);
    lines.push('');
  }

  lines.push('## Fix list, highest impact first');
  lines.push('');
  if (ranked.length === 0) {
    lines.push('Nothing actionable found offline. Run the networked skills for competitive and citation gaps.');
    lines.push('');
  } else {
    ranked.forEach((r, i) => {
      const surfaceTags = r.surfaces.map((s) => s.toUpperCase()).join(' / ');
      lines.push(`### ${i + 1}. ${r.title} — ${r.status === 'fail' ? '**failing**' : 'weak'}`);
      lines.push('');
      lines.push(`\`${r.id}\` · moves **${surfaceTags}** · ${CATEGORIES[r.category].label}${r.confidence === 'speculative' ? ' · ⚠ speculative, see note' : ''}`);
      lines.push('');
      lines.push(`**Found:** ${r.evidence}`);
      lines.push('');
      lines.push(`**Fix:** ${r.fix}`);
      lines.push('');
    });
  }

  const skipped = results.filter((r) => r.status === 'skip' && r.fix);
  if (skipped.length) {
    lines.push('## Could not verify offline');
    lines.push('');
    lines.push('These need the GitHub API or the open web. They are excluded from the score rather than guessed at.');
    lines.push('');
    for (const r of skipped) {
      lines.push(`- **${r.title}** — ${r.evidence}${r.fix ? ` ${r.fix}` : ''}`);
    }
    lines.push('');
  }

  lines.push('## Full check inventory');
  lines.push('');
  lines.push('| | Check | Category | Surfaces | Evidence |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const r of results) {
    const ev = r.evidence.replace(/\|/g, '\\|').slice(0, 120);
    lines.push(`| ${ICON[r.status]} | ${r.title} | ${CATEGORIES[r.category].label} | ${r.surfaces.join(', ')} | ${ev} |`);
  }
  lines.push('');

  lines.push('## What this audit does not know');
  lines.push('');
  lines.push('This pass reads the working tree only. It cannot see who your competitors are, which queries developers actually use for your category, which third-party pages currently get cited instead of you, or whether any engine mentions you today. Those need the networked skills — `category-profile` and `citation-probe` — which write into the same `.reporise/profile.json` this report sits beside.');
  lines.push('');
  lines.push('A perfect score here means the repo is well-formed for retrieval. It does not mean anyone is retrieving it.');
  lines.push('');

  return lines.join('\n');
}
